version: '2'
services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules/
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://db:27017/db
      - DEBUG=boot
    links:
      - db
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
